export { default as Home } from './Home/Home'
export { default as SearchDrug } from './SearchDrug/SearchDrug'
export { default as DocumentationList } from './Documentations/List/List'
export { default as DocumentationView } from './Documentations/View/View'
export { default as GiveAdvice } from './GiveAdvice/GiveAdvice'